# permissions for end users to edit etcdpeers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcdpeer-editor-role
rules:
- apiGroups:
  - etcd.improbable.io.my.domain
  resources:
  - etcdpeers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etcd.improbable.io.my.domain
  resources:
  - etcdpeers/status
  verbs:
  - get
