# permissions for end users to view etcdpeers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcdpeer-viewer-role
rules:
- apiGroups:
  - etcd.improbable.io.my.domain
  resources:
  - etcdpeers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - etcd.improbable.io.my.domain
  resources:
  - etcdpeers/status
  verbs:
  - get
